### PR TITLE
Simplify `PolynomialCommitment` trait: remove the generic on `S: CryptographicSponge`

### PR DESCRIPTION
**Pull request by mmagician**
## Description

Quality of life improvement for downstream users of the library.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by autquis — COMMENTED** [review]
Much better, indeed!

**Comment by autquis** [comment]
I pushed this to make the tests pass. I can also open another PR to the master for this and then you can rebase this one on that; let me know.

**Comment by mmagician** [comment]
@autquis Thank you!

**Comment by mmagician** [comment]
It's a bit annoying with that stable/nightly discrepancy on imports

**Comment by mmagician** [comment]
@autquis I had to undo your changes, as no-std was failing. In the end I ended up following the same strategy as https://github.com/arkworks-rs/algebra/pull/790/files#diff-6035356f5adc30af6393d5492dbc1d9d8ec187272030fdd95709b1b30f1275fc

**Comment by autquis** [comment]
I wonder, isn't it clenaer if we use `#[cfg(not(feature = "std"))]` for these imports?

**Comment by mmagician** [comment]
The checks in #130 are failing. They've already been addressed here, we can either try to cherry pick the relevant commit to Hyrax, or merge this PR first and adapt Hyrax accordingly to remove the generic `S`. I'm in favor of the latter @Pratyush

**Comment by autquis** [comment]
I added `ark-std` to the patch due to arkworks-rs/ark-std#48.
CI fails because of the same issue of imports in `crypto-primitive`. But `poly-commit` is fine now.

Also, I am doing a bit of cleaning up in the order of imports, as we are touching imports anyway.

**Comment by autquis** [comment]
This PR depends now on arkworks-rs/crypto-primitive#142. Once that is merged, we can update `Cargo.toml`.

**Comment by autquis** [comment]
The PR is ready to be merged. @z-tech @Pratyush @weikengchen

**Comment by autquis** [comment]
Ping! Once this gets merged, I can move to the other PRs (Hyrax, Brakedown) and prepare them for being merged.

**Comment by autquis** [comment]
Another ping. @weikengchen @Pratyush @z-tech 

Also, it seems the `cfg(not(feature("std")))` is no longer needed (rustc stable got upgraded). Once you review this, I'll remove them, and then, merge the PR, please. I'm not changing it now.

**Comment by autquis** [comment]
Gentle reminder @Pratyush

**Comment by autquis** [comment]
Reminder for this @Pratyush I would appreciate it if you could have a look

**Review by Pratyush — APPROVED** [review]

**Comment by Pratyush** [comment]
The CI build failure is puzzling; DefaultHashBuilder does implement Clone…

https://docs.rs/hashbrown/latest/hashbrown/type.DefaultHashBuilder.html

**Comment by autquis** [comment]
@Pratyush  Thanks for checking! There were two issues:
- I had upgraded the `hashbrown` version to `0.14`. I changed it back to `0.13`. I tried to figure out the root cause, but I didn't manage. If we use the `default-hasher` feature from `hashbrown`, that would solve the problem. In any case, I changed it back to `0.13` for now. The most recent version is `0.15`.
- The issue #154 

Now CI is okay.

**Comment by autquis** [comment]
Just a reminder to add this to the merge queue :) @Pratyush

**Comment by Pratyush** [comment]
Regarding the dummy doc, could you change it so that in the test modules we have `#![allow(missing_docs)]`? This way we don't need to add these dummy docs. Thank you!

**Comment by autquis** [comment]
Done! :)

**Pull request merged**
